### PR TITLE
Feature/hardening

### PR DESCRIPTION
**Pull request by morancj**
Split parameters to `docker run` to simplify reviews and highlight important changes.
Remove stale bind mount of user's `$HOME` and old `$GEM_PATH`.
Drop all Linux Capabilities when running the container.

### CODE REVIEW

**Comment by pcolmer** [comment]
This is an out of date version of the build script. The new script is much cleaner and does very little :).

I'd prefer the PR to cover just one thing - the hardening - and have a separate PR deal with cleaning up the site build script.

**Comment by morancj** [comment]
> This is an out of date version of the build script. The new script is much cleaner and does very little :).
> 
> I'd prefer the PR to cover just one thing - the hardening - and have a separate PR deal with cleaning up the site build script.

As per this change? [dae2f91](https://github.com/ArmNNWebsite/website/pull/33/commits/dae2f913b1e0e94eff770ab7851e42df4c671a4c)

**Comment by morancj** [comment]
> This is an out of date version of the build script. The new script is much cleaner and does very little :).
> 
> I'd prefer the PR to cover just one thing - the hardening - and have a separate PR deal with cleaning up the site build script.

`

**Comment by morancj** [comment]
Can try this out with e.g:
```bash
JEKYLL_ACTION=serve \
JEKYLLSITEBUILD=latest \
JEKYLL_ENV=staging \
JEKYLL_CONFIG="_config.yml,_config-$JEKYLL_ENV.yml" \
docker run --rm \
 --cap-drop ALL \
 -it -p 4000:4000 -e JEKYLL_CONFIG -e JEKYLL_ENV \
 -v /etc/passwd:/etc/passwd:ro \
 -v /etc/group:/etc/group:ro \
 -u "$(id -u)":"$(id -g)" \
 -v "$(pwd)/.gems:/gems" \
 -v "$(pwd)":/srv/source \
 linaroits/jekyllsitebuild:"$JEKYLLSITEBUILD" \
 build-site.sh
```

**Comment by pcolmer** [comment]
> JEKYLL_CONFIG="_config.yml,_config-$JEKYLL_ENV.yml"

That bit isn't needed on the latest container. Just FYI.

**Comment by pcolmer** [comment]
And, as per your original PR:

> -v "$(pwd)/.gems:/gems" \

This isn't needed either.

**Comment by pcolmer** [comment]
Which is why I was trying to keep the changes separated over different PRs :). It is a bit of a challenge trying to get all of the websites updated with the latest version of the build script all at once.

**Comment by morancj** [comment]
That will teach me to copy the wrong command!
Try this:
```bash
JEKYLL_ACTION=serve \
JEKYLLSITEBUILD=latest \
JEKYLL_ENV=staging \
docker run --rm \
 --cap-drop ALL \
 -it -p 4000:4000 \
 -e JEKYLL_ENV \
 -v /etc/passwd:/etc/passwd:ro \
 -v /etc/group:/etc/group:ro \
 -u "$(id -u)":"$(id -g)" \
 -v "$(pwd)":/srv/source \
 linaroits/jekyllsitebuild:"$JEKYLLSITEBUILD" \
 build-site.sh
```

**Pull request merged**
